### ISSUE TITLE
Information tab at the top navbar needs to be moved to the far right

### ISSUE THREAD

**Issue by gbcoates** [SCGeology/riverPortal#10]
Need to figure out how to get style="float: right" to work correctly.

**Comment by gbcoates** [comment]
I have found a way for this to work.

Instead of including the final information tab within the original un-ordered list:
1. Cloned the original list to just include the information tab in the second list
2. Used a local style to float the tab to the right of the page 

Everything looks to be working correctly.

**Comment by freewheelCarto** [comment]
Looks good, let's make a media query to move it back to the left when in mobile mode. 

Let's add the word 'About' to the right of the icon.

**Comment by freewheelCarto** [comment]
I think we're good here.
