### ISSUE TITLE
Device screen resolution issues

### ISSUE THREAD

**Issue by gbcoates** [SCGeology/riverPortal#11]
Using Google Chrome's mobile device screen size emulator, I have noticed some issues.

1. Top navbar is displaying in a non-user-friendly way with screen resolution widths between: 768 - 840
![image](https://cloud.githubusercontent.com/assets/20017664/17296100/7e32b69a-57cd-11e6-8082-9435bc366045.png)

2. Initial page load sidebar takes up a lot of page with iPad screen resolution (768 x 1024)

3. Mobile device navbar's dropdown might should  be rearranged since information tab is floated to far right
![image](https://cloud.githubusercontent.com/assets/20017664/17296083/664a9a98-57cd-11e6-9d13-550603d7a8e6.png)

**Comment by freewheelCarto** [comment]
This should be fixed right now based on the new navbar menu, but we will leave this issue open to make sure that it continues to work well as we continue to develop.

**Comment by freewheelCarto** [comment]
I think we're good on this!
