### ISSUE TITLE
Add connected rivers

### ISSUE THREAD

**Issue by freewheelCarto** [SCGeology/riverPortal#15]
It would be cool to have a button that would allow you to add all connected rivers to a currently selected river via the Find a River tool. 

This could be set up in the database by creating a field for 'connected rivers' that would list all of the rivers connected upstream and downstream. 

The application could parse out this list, query the service for the points on the listed rivers, and return those to the map.

**Comment by gbcoates** [comment]
I really like that idea. I'll start setting that up in the database.

**Comment by freewheelCarto** [comment]
This will also help with reporting on error on the float plan tool.  You could easily check to see if the end point's streamName is in the connected rivers list of the start point. This would allow you to warn the user earlier in the process.

**Comment by freewheelCarto** [comment]
This functionality is now working and available for when the data are filtered by River Name.  Otherwise, I haven't messed with it yet.  Not sure if I will.
