### ISSUE TITLE
Near Modal Redo

### ISSUE THREAD

**Issue by gbcoates** [SCGeology/riverPortal#20]
Instead of auto-populating the address and city boxes using the reverse-geocoder, have the boxes gray and use the lat-long point for the position.

This will help solve the problem of some devices not auto-populating when the location button is used.

**Comment by freewheelCarto** [comment]
Made the changes.

disables the address input forms when clicked
adds a dot where the locate button returns lat lng
gives success message if location found
gives error message if it doesn't work (I think)

can toggle on and off by clicking button.
