### ISSUE TITLE
Near Modal Geolocator button

### ISSUE THREAD

**Issue by gbcoates** [SCGeology/riverPortal#5]
Need to figure out how to extract lat/long data from leaflet geolocator function

**Comment by gbcoates** [comment]
Figured out how to auto populate "Access Near You" inputs from just pressing "Locate Me" button.

Use of ESRI Leaflet **reverse** geocoder to find the location of the user and then extracting the returned address and city to automatically input into the query.

I have ran this successfully in FireFox but did not run successfully in IE. Still have to yet to test Chrome due to https location issue.

**Comment by gbcoates** [comment]
"Use Current Location" button works successfully on most devices. It is still is not working correctly on Internet Explorer.

**Comment by freewheelCarto** [comment]
See this issue https://github.com/SCGeology/riverPortal/issues/20
